name: CNRE
run: sbi.cnre.run
device: cpu
params:
  num_rounds: 1
  neural_net: resnet
  hidden_features: 50
  simulation_batch_size: 1000
  training_batch_size: 512
  num_atoms: 10
  automatic_transforms_enabled: true
  sample_with: rejection
  mcmc_parameters:
    num_chains: 100
    thin: 10
    warmup_steps: 100
    init_strategy: sir
    sir_batch_size: 1000
    sir_num_batches: 100
    reuse: true
  z_score_x: independent
  z_score_theta: independent
  max_num_epochs: ???
  alpha: 1.0
