name: SNPE
run: sbi.snpe.run
device: cpu
params:
  num_rounds: 10
  neural_net: nsf
  hidden_features: 50
  simulation_batch_size: 1000
  training_batch_size: 512
  num_atoms: 10
  automatic_transforms_enabled: false
  z_score_x: independent
  z_score_theta: independent
