name: cnre
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - numpy<2.0
  # fixing the following 3 makes the install work for me
  - pytorch::pytorch==1.13.1=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch::pytorch-cuda=11.7
  - mkl=2022.2.1  # might work: mkl<2024
  - jupyter
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pytest
  - black
  - isort
  - scikit-learn
  - pip
  - pip:
    - pyro-ppl==1.8.0
    - hydra-core==1.1.1
    - hydra-joblib-launcher==1.1.5
    - hydra-submitit-launcher==1.1.6
    - pytorch-lightning==1.6.3
    - corner
    - -e remote/diffeqtorch
    - -e remote/sbi
    - -e remote/sbibm
    - -e .
