[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "basicpython/__version__.py"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3
skip_gitignore = true
line_length = 88
