defaults:
  - submitit_slurm

timeout_min: 60
cpus_per_task: 8
gpus_per_node: 1
nodes: 1
partition: defq
constraint: TitanX
exclude: null
additional_parameters:
  gres: gpu:1
setup:
  - module load cuda11.1/toolkit/11.1.1
  - conda activate ~/data/cnre/env
