name: NRE
run: runfuncs.run_cnre
device: cpu
params:
  neural_net: resnet
  hidden_features: 50
  num_blocks: 2
  use_batch_norm: true
  simulation_batch_size: 1000
  training_batch_size: 512
  num_atoms: 10
  automatic_transforms_enabled: true
  sample_with: rejection
  mcmc_parameters:
    num_chains: 100
    thin: 10
    warmup_steps: 100
    init_strategy: sir
    sir_batch_size: 1000
    sir_num_batches: 100
  z_score_x: independent
  z_score_theta: independent
  num_validation_examples: 1_024
  stop_after_epochs: 2147483647
  variant: B
