# Whether to compute metrics after run or not
compute_metrics: true

# Hydra's overrides are used to change to different tasks and algorithms
defaults:
  - algorithm: cnre
  - task: two_moons
  - data: joint
  - algorithm_data: ${algorithm}_${data}
  - _self_

# Device to use, set on per-algorithm basis
device: ${algorithm.device}

# get number of cores
num_cores: ${hydra:launcher.cpus_per_task}

# Seed
seed: null

# how long to train
max_num_epochs: ???
